---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-ubuntu-20.04
    image: ubuntu:20.04
    dockerfile: Dockerfile.j2
    privileged: true
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
verifier:
  name: ansible
