---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-ubuntu-20.04
    image: ubuntu:focal
    privileged: true
provisioner:
  name: ansible
  options:
    vvv: True
#lint: |
#  set -e
#  yamllint .
#  ansible-lint .
verifier:
  name: ansible
