---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-ubuntu-18.04
    dockerfile: Dockerfile.j2
    image: ubuntu:buster
    privileged: true
provisioner:
  name: ansible
  options:
    vvv: True
#lint: |
#  set -e
#  yamllint .
#  ansible-lint .
verifier:
  name: ansible
