---
name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Run Molecule tests
        uses: robertdebock/molecule-action@2.1.0
        with:
          options: --debug
#
#  release:
#    name: Release
#    needs:
#      - test
#    if: startsWith(github.ref, 'refs/tags/')
#    runs-on: ubuntu-latest
#    steps:
#      - name: Publish to Ansible Galaxy
#        uses: robertdebock/galaxy-action@1.0.3
#        with:
#          galaxy_api_key: ${{ secrets.ansible_galaxy_api_key }}
