---
name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Switch to using Python 3.8 by default
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Install dependencies
        run: |
          echo $(pwd)
          ls -lah
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Test with molecule
        run: |
          molecule --debug converge
#
#  release:
#    name: Release
#    needs:
#      - test
#    if: startsWith(github.ref, 'refs/tags/')
#    runs-on: ubuntu-latest
#    steps:
#      - name: Publish to Ansible Galaxy
#        uses: robertdebock/galaxy-action@1.0.3
#        with:
#          galaxy_api_key: ${{ secrets.ansible_galaxy_api_key }}
